import UIKit

#if canImport(ViafouraSDK)
import ViafouraSDK

func resolveCustomizableView(_ customView: VFCustomizableView) -> (type: String, view: UIView)? {
  switch customView {
  case .postButton(let button):
    return ("postButton", button)
  case .postTextView(let textField):
    return ("postTextView", textField)
  case .postCloseImage(let image):
    return ("postCloseImage", image)
  case .postUserImage(let image):
    return ("postUserImage", image)
  case .postUserAvatar(let avatar):
    return ("postUserAvatar", avatar)
  case .postMetadataTitle(let label):
    return ("postMetadataTitle", label)
  case .postMetadataImage(let image):
    return ("postMetadataImage", image)
  case .postMetadataDescription(let label):
    return ("postMetadataDescription", label)
  case .postHeaderDescription(let label):
    return ("postHeaderDescription", label)
  case .postPlaceholderLabel(let label):
    return ("postPlaceholderLabel", label)
  case .postImageSkeletonView(let skeletonView):
    return ("postImageSkeletonView", skeletonView)
  case .postTitleSkeletonView(let skeletonView):
    return ("postTitleSkeletonView", skeletonView)
  case .postDescriptionSkeletonView(let skeletonView):
    return ("postDescriptionSkeletonView", skeletonView)
  case .postBackgroundView(let view):
    return ("postBackgroundView", view)
  case .profileNameLabel(let label):
    return ("profileNameLabel", label)
  case .profileLogoutLabel(let label):
    return ("profileLogoutLabel", label)
  case .profileCloseImage(let image):
    return ("profileCloseImage", image)
  case .profileLikesLabel(let label):
    return ("profileLikesLabel", label)
  case .profileFollowersLabel(let label):
    return ("profileFollowersLabel", label)
  case .profileSegmentedControl(let segmentedControl):
    return ("profileSegmentedControl", segmentedControl)
  case .profileCommunityTabView(let tabView):
    return ("profileCommunityTabView", tabView)
  case .profileFollowView(let view):
    return ("profileFollowView", view)
  case .profileBackgroundView(let view):
    return ("profileBackgroundView", view)
  case .commentCellExpandRepliesLoading(let loadingView):
    return ("commentCellExpandRepliesLoading", loadingView)
  case .commentCellExpandRepliesImage(let image):
    return ("commentCellExpandRepliesImage", image)
  case .commentCellExpandRepliesLabel(let label):
    return ("commentCellExpandRepliesLabel", label)
  case .commentCellDateLabel(let label):
    return ("commentCellDateLabel", label)
  case .commentCellNameLabel(let label):
    return ("commentCellNameLabel", label)
  case .commentCellContentLabel(let label):
    return ("commentCellContentLabel", label)
  case .commentCellOptionsButton(let button):
    return ("commentCellOptionsButton", button)
  case .commentCellLikeImage(let image):
    return ("commentCellLikeImage", image)
  case .commentCellLikeLabel(let label):
    return ("commentCellLikeLabel", label)
  case .commentCellDislikeImage(let image):
    return ("commentCellDislikeImage", image)
  case .commentCellTrustedView(let view):
    return ("commentCellTrustedView", view)
  case .commentCellModeratorView(let view):
    return ("commentCellModeratorView", view)
  case .commentCellAuthorView(let view):
    return ("commentCellAuthorView", view)
  case .commentCellFollowView(let view):
    return ("commentCellFollowView", view)
  case .commentCellDislikeLabel(let label):
    return ("commentCellDislikeLabel", label)
  case .commentCellReplyLabel(let label):
    return ("commentCellReplyLabel", label)
  case .commentCellReplyImage(let image):
    return ("commentCellReplyImage", image)
  case .commentCellUserImage(let image):
    return ("commentCellUserImage", image)
  case .commentCellUserAvatar(let view):
    return ("commentCellUserAvatar", view)
  case .commentCellUserIndicator(let image):
    return ("commentCellUserIndicator", image)
  case .commentCellAwaitingModerationView(let view):
    return ("commentCellAwaitingModerationView", view)
  case .commentCellCustomBadge(let badge):
    return ("commentCellCustomBadge", badge)
  case .commentCellPinnedView(let view):
    return ("commentCellPinnedView", view)
  case .commentCellEditorPickView(let view):
    return ("commentCellEditorPickView", view)
  case .commentCellSeparator(let separator):
    return ("commentCellSeparator", separator)
  case .userCommentDescLabel(let label):
    return ("userCommentDescLabel", label)
  case .userCommentOriginalImage(let image):
    return ("userCommentOriginalImage", image)
  case .userCommentOriginalTitle(let label):
    return ("userCommentOriginalTitle", label)
  case .userCommentContentLabel(let label):
    return ("userCommentContentLabel", label)
  case .userCommentSeparator(let separator):
    return ("userCommentSeparator", separator)
  case .userCommentDateLabel(let label):
    return ("userCommentDateLabel", label)
  case .userCellImage(let image):
    return ("userCellImage", image)
  case .userCellAvatarView(let view):
    return ("userCellAvatarView", view)
  case .userCellNameLabel(let label):
    return ("userCellNameLabel", label)
  case .userCellActionDateLabel(let label):
    return ("userCellActionDateLabel", label)
  case .userCellBadgeLabel(let label):
    return ("userCellBadgeLabel", label)
  case .userCellBadgeView(let view):
    return ("userCellBadgeView", view)
  case .userCellSeparator(let separator):
    return ("userCellSeparator", separator)
  case .userCellFollowView(let view):
    return ("userCellFollowView", view)
  case .previewEmptyCommentsView(let emptyCommentsView):
    return ("previewEmptyCommentsView", emptyCommentsView)
  case .previewSeeMoreCommentsButton(let button):
    return ("previewSeeMoreCommentsButton", button)
  case .previewTitleLabel(let label):
    return ("previewTitleLabel", label)
  case .previewPrivacyLabel(let label):
    return ("previewPrivacyLabel", label)
  case .previewUserPromptLabel(let label):
    return ("previewUserPromptLabel", label)
  case .previewLoginLabel(let label):
    return ("previewLoginLabel", label)
  case .previewAuthOrLabel(let label):
    return ("previewAuthOrLabel", label)
  case .previewSignupLabel(let label):
    return ("previewSignupLabel", label)
  case .previewUserImage(let image):
    return ("previewUserImage", image)
  case .previewUserAvatar(let avatar):
    return ("previewUserAvatar", avatar)
  case .previewUserSomeoneWritingLabel(let label):
    return ("previewUserSomeoneWritingLabel", label)
  case .previewNewCommentsNotificationView(let view):
    return ("previewNewCommentsNotificationView", view)
  case .previewCommentPrompt(let view):
    return ("previewCommentPrompt", view)
  case .previewNotificationBellView(let view):
    return ("previewNotificationBellView", view)
  case .previewHeaderView(let view):
    return ("previewHeaderView", view)
  case .previewSortImage(let image):
    return ("previewSortImage", image)
  case .previewSortLabel(let label):
    return ("previewSortLabel", label)
  case .previewAllComments(let view):
    return ("previewAllComments", view)
  case .previewPoweredByView(let poweredByView):
    return ("previewPoweredByView", poweredByView)
  case .previewSkeletonView(let skeletonView):
    return ("previewSkeletonView", skeletonView)
  case .previewFollowView(let followView):
    return ("previewFollowView", followView)
  case .previewBackgroundView(let view):
    return ("previewBackgroundView", view)
  case .reportReasonOptionLabel(let label):
    return ("reportReasonOptionLabel", label)
  case .reportTitleLabel(let label):
    return ("reportTitleLabel", label)
  case .reportPickReasonLabel(let label):
    return ("reportPickReasonLabel", label)
  case .reportStartCloseLabel(let label):
    return ("reportStartCloseLabel", label)
  case .reportStartDescriptionLabel(let label):
    return ("reportStartDescriptionLabel", label)
  case .reportStartButton(let button):
    return ("reportStartButton", button)
  case .reportChosenTitleLabel(let label):
    return ("reportChosenTitleLabel", label)
  case .reportChosenDescriptionLabel(let label):
    return ("reportChosenDescriptionLabel", label)
  case .reportChosenCloseLabel(let label):
    return ("reportChosenCloseLabel", label)
  case .reportChosenButton(let button):
    return ("reportChosenButton", button)
  case .reportThanksLabel(let label):
    return ("reportThanksLabel", label)
  case .reportThanksButton(let button):
    return ("reportThanksButton", button)
  case .trendingVerticalBackgroundView(let view):
    return ("trendingVerticalBackgroundView", view)
  case .trendingVerticalTitleLabel(let label):
    return ("trendingVerticalTitleLabel", label)
  case .trendingVerticalFullImage(let image):
    return ("trendingVerticalFullImage", image)
  case .trendingVerticalFullImageIcon(let image):
    return ("trendingVerticalFullImageIcon", image)
  case .trendingVerticalFullTitle(let label):
    return ("trendingVerticalFullTitle", label)
  case .trendingVerticalFullCount(let label):
    return ("trendingVerticalFullCount", label)
  case .trendingVerticalViewMoreButton(let button):
    return ("trendingVerticalViewMoreButton", button)
  case .trendingVerticalCondensedTitle(let label):
    return ("trendingVerticalCondensedTitle", label)
  case .trendingVerticalCondensedCount(let label):
    return ("trendingVerticalCondensedCount", label)
  case .trendingCarouselTitle(let label):
    return ("trendingCarouselTitle", label)
  case .trendingCarouselImage(let image):
    return ("trendingCarouselImage", image)
  case .trendingCarouselCount(let label):
    return ("trendingCarouselCount", label)
  case .trendingCarouselBackgroundView(let view):
    return ("trendingCarouselBackgroundView", view)
  case .bottomPickerView(let view):
    return ("bottomPickerView", view)
  case .bottomPickerTitle(let label):
    return ("bottomPickerTitle", label)
  case .bottomPickerTitleLabel(let label):
    return ("bottomPickerTitleLabel", label)
  case .bottomPickerLabel(let label, _):
    return ("bottomPickerLabel", label)
  case .bottomPickerSeparator(let separatorView):
    return ("bottomPickerSeparator", separatorView)
  case .chatCellContentLabel(let label):
    return ("chatCellContentLabel", label)
  case .chatCellDateLabel(let label):
    return ("chatCellDateLabel", label)
  case .chatCellUserNameLabel(let label):
    return ("chatCellUserNameLabel", label)
  case .chatPostView(let view):
    return ("chatPostView", view)
  case .chatPostImage(let image):
    return ("chatPostImage", image)
  case .chatPostLoading(let loadingView):
    return ("chatPostLoading", loadingView)
  case .chatTextView(let textView):
    return ("chatTextView", textView)
  case .chatBackgroundView(let backgroundView):
    return ("chatBackgroundView", backgroundView)
  case .chatLoading(let loadingView):
    return ("chatLoading", loadingView)
  case .chatLoadingMore(let loadingView):
    return ("chatLoadingMore", loadingView)
  case .chatEmptyView(let emptyView):
    return ("chatEmptyView", emptyView)
  case .notificationContentImage(let image):
    return ("notificationContentImage", image)
  case .notificationRemoveImage(let image):
    return ("notificationRemoveImage", image)
  case .notificationTrendingCountImage(let image):
    return ("notificationTrendingCountImage", image)
  case .notificationTrendingImage(let image):
    return ("notificationTrendingImage", image)
  case .notificationTrendingIcon(let image):
    return ("notificationTrendingIcon", image)
  case .notificationGroupTitleLabel(let label):
    return ("notificationGroupTitleLabel", label)
  case .notificationBellText(let label):
    return ("notificationBellText", label)
  case .notificationBellIcon(let icon):
    return ("notificationBellIcon", icon)
  case .conversationStarterBackgroundView(let view):
    return ("conversationStarterBackgroundView", view)
  case .conversationStarterHeaderLabel(let label):
    return ("conversationStarterHeaderLabel", label)
  case .conversationStarterTitleLabel(let label):
    return ("conversationStarterTitleLabel", label)
  case .conversationStarterDescriptionLabel(let label):
    return ("conversationStarterDescriptionLabel", label)
  case .conversationStarterFeaturedCommentLabel(let label):
    return ("conversationStarterFeaturedCommentLabel", label)
  case .conversationStarterActionButton(let button):
    return ("conversationStarterActionButton", button)
  case .liveQuestionCellUserAvatar(let avatar):
    return ("liveQuestionCellUserAvatar", avatar)
  case .liveQuestionCellUserImage(let image):
    return ("liveQuestionCellUserImage", image)
  case .liveQuestionCellUserNameLabel(let label):
    return ("liveQuestionCellUserNameLabel", label)
  case .liveQuestionCellDateLabel(let label):
    return ("liveQuestionCellDateLabel", label)
  case .liveQuestionCellContentLabel(let label):
    return ("liveQuestionCellContentLabel", label)
  case .liveQuestionCellLikeButton(let button):
    return ("liveQuestionCellLikeButton", button)
  case .liveQuestionCellLikeLabel(let label):
    return ("liveQuestionCellLikeLabel", label)
  case .liveQuestionCellDislikeButton(let button):
    return ("liveQuestionCellDislikeButton", button)
  case .liveQuestionCellDislikeLabel(let label):
    return ("liveQuestionCellDislikeLabel", label)
  case .liveQuestionCellReplyButton(let button):
    return ("liveQuestionCellReplyButton", button)
  case .liveQuestionCellOptionsButton(let button):
    return ("liveQuestionCellOptionsButton", button)
  case .liveQuestionCellReplyingToLabel(let label):
    return ("liveQuestionCellReplyingToLabel", label)
  case .liveQuestionCellPinnedView(let view):
    return ("liveQuestionCellPinnedView", view)
  case .liveQuestionCellHostPillView(let view):
    return ("liveQuestionCellHostPillView", view)
  case .liveQuestionCellSeparator(let view):
    return ("liveQuestionCellSeparator", view)
  case .liveQuestionCellAnnouncementLabel(let label):
    return ("liveQuestionCellAnnouncementLabel", label)
  case .liveQuestionCellAnnouncementIcon(let image):
    return ("liveQuestionCellAnnouncementIcon", image)
  case .liveQuestionCellAnnouncementBackground(let view):
    return ("liveQuestionCellAnnouncementBackground", view)
  case .liveQuestionCellAnswerLabel(let label):
    return ("liveQuestionCellAnswerLabel", label)
  case .liveQuestionCellAnswerIcon(let image):
    return ("liveQuestionCellAnswerIcon", image)
  case .liveQuestionCellAnswerBackground(let view):
    return ("liveQuestionCellAnswerBackground", view)
  case .liveQuestionsHostCellNameLabel(let label):
    return ("liveQuestionsHostCellNameLabel", label)
  case .liveQuestionsHostCellBadgeLabel(let label):
    return ("liveQuestionsHostCellBadgeLabel", label)
  case .liveQuestionsHostCellBadgePillView(let view):
    return ("liveQuestionsHostCellBadgePillView", view)
  case .liveQuestionsHostCellContainerView(let view):
    return ("liveQuestionsHostCellContainerView", view)
  case .liveQuestionsHostsListBackgroundView(let view):
    return ("liveQuestionsHostsListBackgroundView", view)
  case .liveQuestionComposerUserAvatar(let view):
    return ("liveQuestionComposerUserAvatar", view)
  case .liveQuestionComposerUserImage(let image):
    return ("liveQuestionComposerUserImage", image)
  case .liveQuestionComposerHintLabel(let label):
    return ("liveQuestionComposerHintLabel", label)
  case .liveQuestionComposerPillView(let view):
    return ("liveQuestionComposerPillView", view)
  case .liveQuestionTitleLabel(let label):
    return ("liveQuestionTitleLabel", label)
  case .liveQuestionPoweredByView(let view):
    return ("liveQuestionPoweredByView", view)
  case .liveQuestionBackgroundView(let view):
    return ("liveQuestionBackgroundView", view)
  case .liveQuestionStatusChipView(let view):
    return ("liveQuestionStatusChipView", view)
  case .liveQuestionStatusDotView(let view):
    return ("liveQuestionStatusDotView", view)
  case .liveQuestionStatusLabel(let label):
    return ("liveQuestionStatusLabel", label)
  case .postReplyToUserImage(let view):
    return ("postReplyToUserImage", view)
  case .postReplyToUserAvatar(let view):
    return ("postReplyToUserAvatar", view)
  case .profileNotificationSettingsImage(let view):
    return ("profileNotificationSettingsImage", view)
  case .profileActivityLabel(let view):
    return ("profileActivityLabel", view)
  case .profileCommentsLabel(let view):
    return ("profileCommentsLabel", view)
  case .profileUserImage(let view):
    return ("profileUserImage", view)
  case .profileUserAvatar(let view):
    return ("profileUserAvatar", view)
  case .profileMuteView(let view):
    return ("profileMuteView", view)
  case .commentCellUrlPreviewContainer(let view):
    return ("commentCellUrlPreviewContainer", view)
  case .commentCellUrlPreviewTitleLabel(let view):
    return ("commentCellUrlPreviewTitleLabel", view)
  case .commentCellUrlPreviewDescriptionLabel(let view):
    return ("commentCellUrlPreviewDescriptionLabel", view)
  case .commentCellUrlPreviewSiteNameLabel(let view):
    return ("commentCellUrlPreviewSiteNameLabel", view)
  case .writeReplyUserImage(let view):
    return ("writeReplyUserImage", view)
  case .writeReplyUserAvatar(let view):
    return ("writeReplyUserAvatar", view)
  case .userCellMuteView(let view):
    return ("userCellMuteView", view)
  case .previewCommentsBottomSeparator(let view):
    return ("previewCommentsBottomSeparator", view)
  case .bottomPickerIcon(let view):
    return ("bottomPickerIcon", view)
  case .notificationAvatarView(let view):
    return ("notificationAvatarView", view)
  case .notificationContentLabel(let view):
    return ("notificationContentLabel", view)
  case .notificationDateLabel(let view):
    return ("notificationDateLabel", view)
  case .pollQuestionLabel(let view):
    return ("pollQuestionLabel", view)
  case .pollHeaderLabel(let view):
    return ("pollHeaderLabel", view)
  case .pollHeaderImage(let view):
    return ("pollHeaderImage", view)
  case .pollDeleteLabel(let view):
    return ("pollDeleteLabel", view)
  case .pollDeleteImage(let view):
    return ("pollDeleteImage", view)
  case .pollCloseLabel(let view):
    return ("pollCloseLabel", view)
  case .pollCloseImage(let view):
    return ("pollCloseImage", view)
  case .pollBackgroundView(let view):
    return ("pollBackgroundView", view)
  case .pollOptionLabel(let view):
    return ("pollOptionLabel", view)
  case .pollOptionPercentageLabel(let view):
    return ("pollOptionPercentageLabel", view)
  case .pollOptionVotedImage(let view):
    return ("pollOptionVotedImage", view)
  case .pollOptionRadioImage(let view):
    return ("pollOptionRadioImage", view)
  case .pollOptionFillView(let view):
    return ("pollOptionFillView", view)
  case .pollOptionContainerView(let view):
    return ("pollOptionContainerView", view)
  @unknown default:
    return nil
  }
}
#endif
